---
# chocomilk vars

# Package Changelog
changelog: 'https://helpx.adobe.com/creative-cloud/release-note/cc-release-notes.html'

# Regex for Version
version: "{{ register_changelog.content |
  regex_search('.*<p>Version.*') |
  regex_search('(\\d+)(.)(\\d+)(.)(\\d+)(.)(\\d+)')
  }}"

# Download URL
url: 'https://ccmdls.adobe.com/AdobeProducts/KCCC/1/win32/CreativeCloudSet-Up.exe'
# url64:

searchreplace:
  'tools/chocolateyinstall.ps1':
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: '$checksumPackage = "{{ file_hash }}"'

# readme to description
readme:
  start: 5
  end: 13

# deploy
deploy:
  - provider: chocolatey
    repository: 'https://nuget.itigo.tech/upload'
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: github
    name: 'itigo-bot'
    email: 'chocomilk@itigo.ch'
    url: github.com/itigoag/chocolatey.airtame.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://matters.itigo.tech'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'software-packages'
